/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS = "MENU_CHANGE_HAS_SUB_ITEM_STATUS";

/* USERAPP */
export const USER_GET_LIST = "USER_GET_LIST";
export const USER_GET_LIST_SUCCESS = "USER_GET_LIST_SUCCESS";
export const USER_GET_LIST_ERROR = "USER_GET_LIST_ERROR";
export const USER_GET_LIST_WITH_FILTER = "USER_GET_LIST_WITH_FILTER";
export const USER_GET_LIST_WITH_ORDER = "USER_GET_LIST_WITH_ORDER";
export const USER_GET_LIST_SEARCH = "USER_GET_LIST_SEARCH";
export const USER_ADD_ITEM = "USER_ADD_ITEM";
export const USER_ADD_ITEM_SUCCESS = "USER_ADD_ITEM_SUCCESS";
export const USER_ADD_ITEM_ERROR = "USER_ADD_ITEM_ERROR";
export const USER_SELECTED_ITEMS_CHANGE = "USER_SELECTED_ITEMS_CHANGE";

/* PROFILE */
export const PROFILE_GET_LIST = "PROFILE_GET_LIST";
export const PROFILE_GET_LIST_SUCCESS = "PROFILE_GET_LIST_SUCCESS";
export const PROFILE_GET_LIST_ERROR = "PROFILE_GET_LIST_ERROR";
export const PROFILE_GET_LIST_WITH_FILTER = "PROFILE_GET_LIST_WITH_FILTER";
export const PROFILE_GET_LIST_WITH_ORDER = "PROFILE_GET_LIST_WITH_ORDER";
export const PROFILE_GET_LIST_SEARCH = "PROFILE_GET_LIST_SEARCH";
export const PROFILE_ADD_ITEM = "PROFILE_ADD_ITEM";
export const PROFILE_ADD_ITEM_SUCCESS = "PROFILE_ADD_ITEM_SUCCESS";
export const PROFILE_ADD_ITEM_ERROR = "PROFILE_ADD_ITEM_ERROR";
export const PROFILE_SELECTED_ITEMS_CHANGE = "PROFILE_SELECTED_ITEMS_CHANGE";

/* MODULE */
export const MODULE_GET_LIST = "MODULE_GET_LIST";
export const MODULE_GET_LIST_SUCCESS = "MODULE_GET_LIST_SUCCESS";
export const MODULE_GET_LIST_ERROR = "MODULE_GET_LIST_ERROR";
export const MODULE_GET_LIST_WITH_FILTER = "MODULE_GET_LIST_WITH_FILTER";
export const MODULE_GET_LIST_WITH_ORDER = "MODULE_GET_LIST_WITH_ORDER";
export const MODULE_GET_LIST_SEARCH = "MODULE_GET_LIST_SEARCH";
export const MODULE_ADD_ITEM = "MODULE_ADD_ITEM";
export const MODULE_ADD_ITEM_SUCCESS = "MODULE_ADD_ITEM_SUCCESS";
export const MODULE_ADD_ITEM_ERROR = "MODULE_ADD_ITEM_ERROR";
export const MODULE_SELECTED_ITEMS_CHANGE = "MODULE_SELECTED_ITEMS_CHANGE";

/* OPERATION */
export const OPERATION_GET_LIST = "OPERATION_GET_LIST";
export const OPERATION_GET_LIST_SUCCESS = "OPERATION_GET_LIST_SUCCESS";
export const OPERATION_GET_LIST_ERROR = "OPERATION_GET_LIST_ERROR";
export const OPERATION_GET_LIST_WITH_FILTER = "OPERATION_GET_LIST_WITH_FILTER";
export const OPERATION_GET_LIST_WITH_ORDER = "OPERATION_GET_LIST_WITH_ORDER";
export const OPERATION_GET_LIST_SEARCH = "OPERATION_GET_LIST_SEARCH";
export const OPERATION_ADD_ITEM = "OPERATION_ADD_ITEM";
export const OPERATION_ADD_ITEM_SUCCESS = "OPERATION_ADD_ITEM_SUCCESS";
export const OPERATION_ADD_ITEM_ERROR = "OPERATION_ADD_ITEM_ERROR";
export const OPERATION_SELECTED_ITEMS_CHANGE = "OPERATION_SELECTED_ITEMS_CHANGE";

export * from "./menu/actions";
export * from "./settings/actions";
export * from "./auth/actions";

// export * from "./user/actions";
// export * from "./profile/actions";
// export * from "./module/actions";
// export * from "./operation/actions";
